In [56]:
import pandas as pd

# Step 1: Read the CSV file into a DataFrame without setting the first row as the header
df = pd.read_csv('RNA_counts_141024.csv', header=None)

# Step 2: Transpose the DataFrame
df_transposed = df.transpose()

# Step 3: Make the first row the header
new_header = df_transposed.iloc[1]  # First row for the header
df_transposed = df_transposed[2:]    # Take the data less the header row
df_transposed.columns = new_header  # Set the header row as the dataframe header
df2 = pd.read_excel('RNA_Sample_Linking2.xlsx')
df2['Sample ID'] = df2['Sample ID'].str.replace(' ', '_')
df3 = pd.merge(df2, df_transposed, left_on='Sample ID', right_on='Geneid')

/tmp/ipykernel_4503/3717445309.py:4: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('RNA_counts_141024.csv', header=None)

In [35]:
data = pd.read_csv('../radiomics_clinical_Barcroft_12_01_23.csv')

/tmp/ipykernel_4503/886859809.py:1: DtypeWarning: Columns (3909,3911,3912,3915,3916,3917,3920,3921,3922,3923,3928,3929,3930,3931,3939,3941,3944,3945,3946,3950,3951) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../radiomics_clinical_Barcroft_12_01_23.csv')

In [55]:
data.iloc[:,3905:]['Patient.id']

0       NaN
1       NaN
2       NaN
3       NaN
4      10.0
       ...
572       +
573     NaN
574     NaN
575     NaN
576     NaN
Name: Patient.id, Length: 577, dtype: object

In [71]:
df3

,ICBRC,S HBRC Number,Date,Sample ID,Extraction site,Sample Type,SURGICAL,CASE ID,CASE ID2,Geneid,...,ENSG00000198886,ENSG00000210176,ENSG00000210184,ENSG00000210191,ENSG00000198786,ENSG00000198695,ENSG00000210194,ENSG00000198727,ENSG00000210195,ENSG00000210196
0,3224,T18-094,2018-04-26,T18-094_FT2,ovary,Frozen tumour tissue,B-S,12930,NaN,T18-094_FT2,...,356822,0,0,0,86181,30315,6,292258,0,1542
1,3252,T18-122,2018-05-30,T18-122_FT3,Ovary,Frozen tumour tissue,M-S,13291,NaN,T18-122_FT3,...,514373,0,0,1,153942,49281,7,232566,0,2856
2,3316,T18-177,2018-08-01,T18-177_FT1,Ovary,Frozen tumour tissue,M-S,13750,NaN,T18-177_FT1,...,337700,0,0,0,117007,25735,4,140943,0,1761
3,3317,T18-178,2018-08-01,T18-178_FT1,Ovary,Frozen tumour tissue,M-S,14023,NaN,T18-178_FT1,...,394858,0,0,1,188232,53545,9,322627,0,1432
4,3337,T18-196,2018-08-22,T18-196_FT2,Ovary,Frozen tumour tissue,M-S,14056,NaN,T18-196_FT2,...,797593,1,0,0,435291,91001,15,611639,0,5889
5,3352,T18-214,2018-09-05,T18-214_FT5,Ovary,Frozen tumour tissue,M-S,14654,NaN,T18-214_FT5,...,304380,1,1,1,222031,55559,8,175969,0,3822
6,3368,T18-224,2018-09-12,T18-224_FT4,Ovary,Frozen tumour tissue,M-S,14024,NaN,T18-224_FT4,...,400667,0,0,0,106887,42525,5,228558,0,1258
7,3398,T18-253,2018-10-16,T18-253_FT2,Ovary,Frozen tumour tissue,M-S,14984,NaN,T18-253_FT2,...,429327,0,0,0,108414,19736,1,164381,0,1392
8,3474,T19-020,2019-01-16,T19-020_FN2,Ovary,Frozen normal tissue,B-S,16106,NaN,T19-020_FN2,...,246473,0,0,0,104050,44834,6,144836,0,1685
9,3476,T19-022,2019-01-17,T19-022_FT1,Ovary,Frozen tumour tissue,M-S,16134,NaN,T19-022_FT1,...,447427,0,0,0,164304,43006,10,227655,0,2329
10,3482,T19-026,2019-01-23,T19-026_FT1,Cyst wall,Frozen tumour tissue,B-S,16208,NaN,T19-026_FT1,...,289553,0,0,0,231501,74691,10,185920,0,1427
11,3504,T19-047,2019-02-12,T19-047_FT1,Ovary,Frozen tumour tissue,B-S,16439,NaN,T19-047_FT1,...,570724,0,0,0,123566,88301,14,276218,0,1653
12,3626,T19-067,2019-03-13,T19-067_FT1,Ovary,Frozen tumour tissue,M-S,16937,NaN,T19-067_FT1,...,316722,0,0,0,65931,25489,7,140885,0,1467
13,3640,T19-169,2019-07-31,T19-169_FT1,Left ovary,Frozen tumour tissue,M-S,18638,NaN,T19-169_FT1,...,256073,0,0,0,28618,13381,4,104663,0,480
14,3648,T19-175,2019-08-27,T19-175_FT1,Right Ovary,Frozen tumour tissue,M-S,18786,NaN,T19-175_FT1,...,294266,1,0,0,93961,34265,4,199752,0,1839
15,3655,T19-183,2019-09-04,T19-183_FT1,Ovary,Frozen tumour tissue,M-S,18853,NaN,T19-183_FT1,...,1884572,1,0,0,475441,81225,13,1764493,0,8662
16,3656,T19-184,2019-09-04,T19-184_FT1,Ovary,Frozen tumour tissue,B-S,18852,NaN,T19-184_FT1,...,620560,0,0,2,369985,121051,23,449706,0,4969
17,3804,T21-035,2021-05-25,T21-035_FT14,Ovary,Frozen tumour tissue,M-S,24354,J303,T21-035_FT14,...,354569,0,0,0,54441,16879,1,118789,0,2224
18,3814,T21-041,2021-06-11,T21-041_FT1,Right Ovary,Frozen tumour tissue,M-S,24690,J341,T21-041_FT1,...,3307654,1,2,1,759638,272612,38,1406499,1,19509
19,3817,T21-044,2021-06-29,T21-044_FT1,Right ovary,Frozen tumour tissue,M-S,24696,J347,T21-044_FT1,...,1134820,0,0,1,306505,64893,2,615427,0,3250
20,3830,T21-057,2021-07-22,T21-057_FT1,Left Ovary,Frozen tumour tissue,M-S,24903,J374,T21-057_FT1,...,958459,0,0,0,147826,33948,6,592174,0,3712
21,3844,T21-066,2021-08-17,T21-066_FT1,Right Ovary,Frozen tumour tissue,M-S,25607,J398,T21-066_FT1,...,409643,0,0,0,214074,57978,2,290599,0,3729
22,3877,T21-100,2021-10-13,T21-100_FN1,Left Ovary,Frozen normal tissue,M-S,25827,J432,T21-100_FN1,...,385370,0,0,0,103058,23196,3,271965,0,2420
23,3883,T21-105,2021-10-19,T21-105_FT1,Left Ovary,Frozen tumour tissue,M-S,25830,J435,T21-105_FT1,...,1023308,0,0,0,387594,123653,18,655837,0,3650
24,3887,T21-109,2021-11-02,T21-109_FT1,Right ovary,Frozen tumour tissue,M-S,25962,J453,T21-109_FT1,...,437580,0,0,1,153612,40396,7,253035,0,1693
25,3888,T21-110,2021-11-02,T21-110_FT1,Right ovary,Frozen tumour tissue,M-S,25961,J452,T21-110_FT1,...,1303914,0,0,0,244295,71819,11,501127,0,3328
26,3889,T21-111,2021-11-03,T21-111_FT2,Right ovary,Frozen tumour tissue,M-S,25970,J461,T21-111_FT2,...,413534,0,0,0,99230,24375,6,161944,0,1798
27,3896,T21-117,2021-11-11,T21-117_FT1,Left tube and ovarian mass,Frozen tumour tissue,M-S,26184,J478,T21-117_FT1,...,645863,0,0,0,44853,16032,2,164815,0,3613
28,3909,T21-129,2021-12-07,T21-129_FT1,Left ovary,Frozen tumour tissue,M-S,26246,j486,T21-129_FT1,...,912849,0,0,0,89895,21034,4,458794,0,1062
29,3913,T21-133,2021-12-16,T21-133_FT1,Right ovary,Frozen tumour tissue,M-S,26246,J630,T21-133_FT1,...,762591,0,0,0,350117,93342,8,400354,0,6156
30,3921,T22-005,2022-01-11,T22-005_FT1,Left Ovarian Tumour,Frozen tumour tissue,M-S,26417,J517,T22-005_FT1,...,453784,0,0,0,127073,32904,3,277563,0,1667
31,3924,T22-009,2022-01-19,T22-009_FT1,Right Ovary,Frozen tumour tissue,M-S,26424,J524,T22-009_FT1,...,1392534,0,0,0,221670,68149,15,896159,0,3295
32,3925,T22-011,2022-01-19,T22-011_FT1,Left Ovary,Frozen tumour tissue,B-S,26425,J525,T22-011_FT1,...,1148862,0,0,0,256905,57891,7,849166,0,3113
33,3926,T22-010,2022-01-20,T22-010_FT1,Left Ovary,Frozen tumour tissue,M-S,26428,J528,T22-010_FT1,...,783222,0,0,1,118403,42338,0,553786,0,5544
34,3944,T22-020,2022-02-02,T22-020_FT14,Left ovary,Frozen tumour tissue,M-S,26604,J547,T22-020_FT14,...,937636,0,0,0,157755,58494,6,592541,0,2983
35,3945,T22-021,2022-02-02,T22-021_FT1,Left ovary,Frozen tumour tissue,M-S,26379,J516,T22-021_FT1,...,698171,0,0,0,197208,45302,9,279181,0,1946
36,3946,T22-022,2022-02-08,T22-022_FT1,Cystic left ovary,Frozen tumour tissue,M-S,26624,J567,T22-022_FT1,...,593487,0,0,0,103620,26959,4,330911,0,1393
37,3957,T22-034,2022-03-09,T22-034_FT1,Left ovary,Frozen tumour tissue,M-S,28376,J623,T22-034_FT1,...,1183064,0,0,1,114688,19842,1,277700,0,4077
38,3958,T22-035,2022-03-15,T22-035_FT1,Left ovary,Frozen tumour tissue,M-S,28376,J613,T22-035_FT1,...,336616,0,0,0,170693,57034,4,193574,0,1214

In [69]:
data

,Unnamed: 0.1,Unnamed: 0,ID,N.voxels,SNS_vol,SNS_area,SNS_s2v,SNS_sph,SNS_sph_dis,SNS_com_1,...,SOLID.DIAMETER,PP,P.FLOW,IRREG,AS,ASCITES,COLOUR.SCORE,CYST,CRESCE,MAHCINE_CORECCTED
0,0,1,11935,144882.000000,144882.000000,291538.000000,2.012280,0.045859,21.830102,18.570425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOLUSON E6
1,1,2,12041,197549.000000,197549.000000,398241.000000,2.016728,0.042007,24.042893,20.382207,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOLUSON E6
2,2,3,12165,107498.000000,107498.000000,216576.000000,2.014698,0.050482,19.808851,16.817131,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOLUSON E6
3,3,4,12287,155532.000000,155532.000000,312892.000000,2.011753,0.044707,22.369625,19.037510,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOLUSON E6
4,4,5,12665,53293.000000,53293.000000,107786.000000,2.022520,0.063540,15.738315,13.275361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VOLUSON S10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,572,573,756,233536.250000,233536.250000,469333.250000,2.009764,0.039234,25.538184,21.770426,...,0.0,0,NA,1.0,1.0,0.0,2.0,LOW LEVEL,0,SAMSUNG W10
573,573,574,757,171948.400000,171948.400000,345942.800000,2.012222,0.043817,22.981643,19.552589,...,0.0,0,NA,1.0,1.0,0.0,1.0,LOW LEVEL,1,SAMSUNG W10
574,574,575,759,130348.666667,130348.666667,262413.333333,2.013769,0.048313,20.913305,17.771700,...,0.0,0,NA,1.0,1.0,0.0,1.0,LOW LEVEL,1,SAMSUNG W10
575,575,576,760,76213.000000,76213.000000,153870.666667,2.019244,0.056766,17.658334,14.936394,...,25.0,0,0,1.0,0.0,0.0,1.0,LOW LEVEL,0,SAMSUNG W10
576,576,577,765,26552.000000,26552.000000,53966.000000,2.032681,0.079951,12.523029,10.476015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SAMSUNG W10

In [67]:
import pandas as pd
import os
import shutil

# Step 1: Read the CSV file into a DataFrame without setting the first row as the header
# Use low_memory=False to avoid DtypeWarning
df = pd.read_csv('RNA_counts_141024.csv', header=None, low_memory=False)

# Step 2: Transpose the DataFrame
df_transposed = df.transpose()

# Step 3: Make the first row the header
new_header = df_transposed.iloc[1]  # First row for the header
df_transposed = df_transposed[2:]    # Take the data less the header row
df_transposed.columns = new_header  # Set the header row as the dataframe header

# Read the Excel file and adjust 'Sample ID' for merging
df2 = pd.read_excel('RNA_Sample_Linking2.xlsx')
df2['Sample ID'] = df2['Sample ID'].str.replace(' ', '_')

# Merge DataFrames
df3 = pd.merge(df2, df_transposed, left_on='Sample ID', right_on='Geneid')

# Define directories
source_directory = '/home/kl2418/Documents/Barcroft/Barcroft_Data_FINAL/'
destination_directory = '/home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/'

# Ensure destination directory exists
if not os.path.exists(destination_directory):
    os.makedirs(destination_directory)

# Iterate over rows in df3 and match CASE ID or CASE ID2 to image files
for index, row in df3.iterrows():
    case_id = str(row['CASE ID ']) if not pd.isna(row['CASE ID ']) else ''  # Ensure case_id is a string
    case_id2 = str(row['CASE ID2']) if not pd.isna(row['CASE ID2']) else ''  # Ensure case_id2 is a string
    
    # Find matching .nii.gz files in the source directory
    for file_name in os.listdir(source_directory):
        if file_name.endswith('.nii.gz'):
            if case_id in file_name or case_id2 in file_name:
                # Full path of the source and destination
                source_file_path = os.path.join(source_directory, file_name)
                destination_file_path = os.path.join(destination_directory, file_name)
                
                # Copy the file to the destination directory
                shutil.copy(source_file_path, destination_file_path)
                print(f"Copied {file_name} to {destination_directory}")

Copied j681_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23533_0009_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24880_0014.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j535_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24002_0009_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j572_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j472_1_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26260_0012_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25840_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23537_0022_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j721_4_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j721_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J738_0013.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25966_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14226_4_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24693_0015.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J689_0011_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18851_0025_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 13520_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23505_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 16331_0001_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26257_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J594_0025.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 2349510.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J746_0019_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14337_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26377no2_6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 12955_41cSegmentationsegnrrd_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J692_0009.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j518_6_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j712_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26419_9n_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26421_-1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j545_6_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J667_0013_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J646_0013.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 12919_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14082_0029_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26190_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24571_0009.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J656_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25609_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23508_8_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J638_0016.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25965_0021_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 175823.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j556_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J735_0014_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26190_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23541_0090.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24574_0004_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24925_0006_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j633_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j545_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14337_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 19443_0036_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J726_0021.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25593_0032_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 11935_6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23738_0019.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25619_0013_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24299_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24461_00221cSegmentationsegnrrd_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24467_0028_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25617_0016.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24316_0018.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23515_0072_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24894_0013.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23948__2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26255_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 13142_0012_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j619_1_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J739_0008_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18352_0007.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 13356_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j611_6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J743_0012.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23740_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J689_0011.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24313_0013.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j599_5.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j715_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j556_5.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25608_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23508_8.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j741_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18785_0010.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J662_0009.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23766_0002.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 13551_0010_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J669_0025_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J738_0005.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 12667_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j545_6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j610_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J646_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25597_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j7015_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J591_0016.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14226_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J630_0008.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J703_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J614_0011_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23557_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25823_0026.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26181_0021_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 15773_0026_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26374_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24466_0028_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23950_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 13600_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25962_0006.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23510_0012.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j532_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23533_0008.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24900_0011_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24700_0021_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j607_7_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J738_0019_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j723_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j570_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18638_0037.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26248_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23536_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26583_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26417_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23737_0014.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23951AC_7.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J726_0021_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24889_0011.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25590_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J669_0024_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j518_6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 19439_0009.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25618_0011.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j532_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26188_0010_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j721_11.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18441_0021_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j705_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24691_0001_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24005_0008_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25835_0014.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25962_0006_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18890_0011.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23771_8.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 175823_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J626_0024.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J756_0004.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23766_0002_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25609_0006_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j494_4_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24357_0027_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j472_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j595_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26249_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j601_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26181_0022.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24894_0013_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26247_0022.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j705_10_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J765_0019.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J660_0005_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25970_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J750_0008_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J689_0015_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 19436_0030_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j491_7.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24316_0018_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23950_2.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24313_0015.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26264_-9_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23769_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18785_0010_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j607_1_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26425_-3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 235087.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24880_0010_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j572_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25843_0017_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24892_0019_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25842_0023.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J710_0029_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J735_0012.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J669_0025.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18638_0034.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25964_0017_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j639_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24313_0013_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24890_0013.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26422_-4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26220_-6.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J660_0003.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J760_0015_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j491_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 25962_0018_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J636_0011_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26175_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26255_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j720_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j609_1.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23556_0034.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23507_0017.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J658_0016_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j578_5.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j655_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 18852_0008_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23943_0012_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23767_0019_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j7332_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j721_8.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J760_0010_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 16286_0033_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J727_0008.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23507_0020_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26608_0007.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J617_0018_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J658_0019.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26428_0020.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j706_3_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j694_5.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26583_5.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 14654_3.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j693_7.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26584_-8_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j620_2_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 23549_0046.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 24699_0022_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j678_4_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26220_5_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26622_0009_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J750_0007_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied J710_0030_seg.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied j609_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 12665_4.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/
Copied 26606_0015.nii.gz to /home/kl2418/Documents/Barcroft/CLIPRNA/images_matched/